# Generated by Django 5.2 on 2025-05-06 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SUKMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('case_config', models.CharField(blank=True, max_length=100)),
                ('unit_of_measurement', models.CharField(max_length=50)),
                ('units_per_packet', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('available', models.PositiveIntegerField(default=0)),
                ('reserved', models.PositiveIntegerField(default=0)),
                ('suk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.sukmaster')),
            ],
        ),
    ]
